version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-net

  api-gateway:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
