version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  api_gateway:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - .:/app
